### ISSUE TITLE
Push descriptor variants of tests not using push layouts

### ISSUE THREAD

**Issue by djdeath** [zmike/vkoverhead#13]
Not sure how this is possible because it used to work.

But I just noticed the push descriptor variants of tests are not creating pipelines using those descriptor layouts.
So non of the push test seem to be testing what the should.

For instance, `layout_basic_push` is not used for anything.

**Comment by zmike** [comment]
Are you sure? Those tests have been refactored into macros https://github.com/zmike/vkoverhead/blob/main/src/vkoverhead.c#L1346 so you won't be able to grep for them.

**Comment by djdeath** [comment]
I guess I was missing that those tests don't do any draws. Sorry for the noise.
