### ISSUE TITLE
Outputted tables should be Markdown-compliant

### ISSUE THREAD

**Issue by qwertychouskie** [zmike/vkoverhead#23]
See https://github.com/zmike/zmike.github.io/discussions/29#discussioncomment-7095888 for one example of why this is desirable.  It would also help make bug reports and merge requests that have `vkoverhead` data more readable.

**Comment by qwertychouskie** [comment]
:eyes: 
![image](https://github.com/zmike/vkoverhead/assets/13989090/7f73d905-124e-4e74-a393-498f1a446a6d)

**Comment by qwertychouskie** [comment]
```
qwerty@qwerty-asus-g14:~/Projects/vkoverhead/builddir$ ./vkoverhead

| Device Name                        | Driver Name | Driver Info |
| ---------------------------------- | ----------- | ----------- |
| NVIDIA GeForce RTX 3060 Laptop GPU | NVIDIA      | 535.86.05   |


|   # | Draw Tests                                          |    kop/s | % relative to 'draw' |
| --: | --------------------------------------------------- | -------: | -----: |
|   0 | draw                                                |    52647 | 100.0% |
|   1 | draw_multi                                          |   227737 | 432.6% |
|   2 | draw_vertex                                         |    54482 | 103.5% |
|   3 | draw_multi_vertex                                   |   225505 | 428.3% |
|   4 | draw_index_change                                   |    38426 |  73.0% |
|   5 | draw_index_offset_change                            |    38052 |  72.3% |
|   6 | draw_rp_begin_end                                   |     1395 |   2.7% |
|   7 | draw_rp_begin_end_dynrender                         |     1019 |   1.9% |
|   8 | draw_rp_begin_end_dontcare                          |     1925 |   3.7% |
|   9 | draw_rp_begin_end_dontcare_dynrender                |     1214 |   2.3% |
|  10 | draw_multirt                                        |    50316 |  95.6% |
|  11 | draw_multirt_dynrender                              |    49386 |  93.8% |
|  12 | draw_multirt_begin_end                              |      482 |   0.9% |
|  13 | draw_multirt_begin_end_dynrender                    |      400 |   0.8% |
|  14 | draw_multirt_begin_end_dontcare                     |      740 |   1.4% |
|  15 | draw_multirt_begin_end_dontcare_dynrender           |      645 |   1.2% |
|  16 | draw_vbo_change                                     |    35652 |  67.7% |
|  17 | draw_1vattrib_change                                |     8197 |  15.6% |
|  18 | draw_16vattrib                                      |    49680 |  94.4% |
|  19 | draw_16vattrib_16vbo_change                         |     9338 |  17.7% |
|  20 | draw_16vattrib_change                               |     8506 |  16.2% |
|  21 | draw_16vattrib_change_dynamic                       |     9299 |  17.7% |
|  22 | draw_16vattrib_change_gpl                           |      324 |   0.6% |
|  23 | draw_16vattrib_change_gpl_hashncache                |     4206 |   8.0% |
|  24 | draw_1ubo_change                                    |    21087 |  40.1% |
|  25 | draw_12ubo_change                                   |     4719 |   9.0% |
|  26 | draw_1combined_sampler_change                       |     9740 |  18.5% |
|  27 | draw_16combined_sampler_change                      |     9357 |  17.8% |
|  28 | draw_1texelbuffer_change                            |    21112 |  40.1% |
|  29 | draw_16texelbuffer_change                           |    19244 |  36.6% |
|  30 | draw_1ssbo_change                                   |    20787 |  39.5% |
|  31 | draw_8ssbo_change                                   |    17057 |  32.4% |
|  32 | draw_1image_change                                  |     9716 |  18.5% |
|  33 | draw_16image_change                                 |     9519 |  18.1% |
|  34 | draw_1imagebuffer_change                            |    20993 |  39.9% |
|  35 | draw_16imagebuffer_change                           |    20194 |  38.4% |
|  36 | draw_ubo_db_change                                  |     4523 |   8.6% |
|  37 | draw_ssbo_db_change                                 |    28640 |  54.4% |
|  38 | draw_combined_sampler_db_change                     |    28817 |  54.7% |
|  39 | draw_image_db_change                                |    28688 |  54.5% |

|   # | Submit Tests                                        |     op/s | % relative to 'submit_noop' |
| --: | --------------------------------------------------- | -------: | -----: |
|  40 | submit_noop                                         | 18453031 | 100.0% |
|  41 | submit_50noop                                       |  5127028 |  27.8% |
|  42 | submit_1cmdbuf                                      |   182807 |   1.0% |
|  43 | submit_50cmdbuf                                     |    12292 |   0.1% |
|  44 | submit_50cmdbuf_50submit                            |    12238 |   0.1% |

|   # | Descriptor Tests                                    |    kop/s | % relative to 'descriptor_noop' |
| --: | --------------------------------------------------- | -------: | -----: |
|  45 | descriptor_noop                                     |   414293 | 100.0% |
|  46 | descriptor_1ubo                                     |   107430 |  25.9% |
|  47 | descriptor_template_1ubo                            |    96163 |  23.2% |
|  48 | descriptor_template_1ubo_push                       |    81682 |  19.7% |
|  49 | descriptor_12ubo                                    |    21969 |   5.3% |
|  50 | descriptor_template_12ubo                           |    20922 |   5.1% |
|  51 | descriptor_template_12ubo_push                      |    12957 |   3.1% |
|  52 | descriptor_1combined_sampler                        |   120383 |  29.1% |
|  53 | descriptor_template_1combined_sampler               |   110941 |  26.8% |
|  54 | descriptor_template_1combined_sampler_push          |    93437 |  22.6% |
|  55 | descriptor_16combined_sampler                       |    25693 |   6.2% |
|  56 | descriptor_template_16combined_sampler              |    24574 |   5.9% |
|  57 | descriptor_template_16combined_sampler_push         |    12239 |   3.0% |
|  58 | descriptor_1sampled_image                           |   125789 |  30.4% |
|  59 | descriptor_template_1sampled_image                  |   121371 |  29.3% |
|  60 | descriptor_template_1sampled_image_push             |    93073 |  22.5% |
|  61 | descriptor_16sampled_image                          |    28869 |   7.0% |
|  62 | descriptor_template_16sampled_image                 |    28451 |   6.9% |
|  63 | descriptor_template_16sampled_image_push            |    12340 |   3.0% |
|  64 | descriptor_1texelbuffer                             |   162074 |  39.1% |
|  65 | descriptor_template_1texelbuffer                    |   144840 |  35.0% |
|  66 | descriptor_template_1texelbuffer_push               |    95636 |  23.1% |
|  67 | descriptor_16texelbuffer                            |    37076 |   8.9% |
|  68 | descriptor_template_16texelbuffer                   |    37256 |   9.0% |
|  69 | descriptor_template_16texelbuffer_push              |    12789 |   3.1% |
|  70 | descriptor_1ssbo                                    |   125223 |  30.2% |
|  71 | descriptor_template_1ssbo                           |   121922 |  29.4% |
|  72 | descriptor_template_1ssbo_push                      |    91633 |  22.1% |
|  73 | descriptor_8ssbo                                    |    38994 |   9.4% |
|  74 | descriptor_template_8ssbo                           |    40857 |   9.9% |
|  75 | descriptor_template_8ssbo_push                      |    20273 |   4.9% |
|  76 | descriptor_1image                                   |   126194 |  30.5% |
|  77 | descriptor_template_1image                          |   123875 |  29.9% |
|  78 | descriptor_template_1image_push                     |    99706 |  24.1% |
|  79 | descriptor_16image                                  |    53751 |  13.0% |
|  80 | descriptor_template_16image                         |    51054 |  12.3% |
|  81 | descriptor_template_16image_push                    |    26386 |   6.4% |
|  82 | descriptor_1imagebuffer                             |   171423 |  41.4% |
|  83 | descriptor_template_1imagebuffer                    |   154875 |  37.4% |
|  84 | descriptor_template_1imagebuffer_push               |    93859 |  22.7% |
|  85 | descriptor_16imagebuffer                            |    65844 |  15.9% |
|  86 | descriptor_template_16imagebuffer                   |    61643 |  14.9% |
|  87 | descriptor_template_16imagebuffer_push              |    25725 |   6.2% |
|  88 | descriptor_buffer_offset_ubo                        |   281042 |  67.8% |
|  89 | descriptor_buffer_offset_combined_sampler           |   304401 |  73.5% |
|  90 | descriptor_buffer_offset_sampled_image              |   353466 |  85.3% |
|  91 | descriptor_buffer_offset_texelbuffer                |   139405 |  33.6% |
|  92 | descriptor_buffer_offset_ssbo                       |   331791 |  80.1% |
|  93 | descriptor_buffer_offset_image                      |   304730 |  73.6% |
|  94 | descriptor_buffer_offset_imagebuffer                |   140123 |  33.8% |
|  95 | descriptor_copy_1ubo                                |   143032 |  34.5% |
|  96 | descriptor_copy_12ubo                               |    29575 |   7.1% |
|  97 | descriptor_copy_1combined_sampler                   |   140687 |  34.0% |
|  98 | descriptor_copy_16combined_sampler                  |    41363 |  10.0% |
|  99 | descriptor_copy_1sampled_image                      |   138371 |  33.4% |
| 100 | descriptor_copy_16sampled_image                     |    40806 |   9.8% |
| 101 | descriptor_copy_1texelbuffer                        |   140494 |  33.9% |
| 102 | descriptor_copy_16texelbuffer                       |    40330 |   9.7% |
| 103 | descriptor_copy_1ssbo                               |   108785 |  26.3% |
| 104 | descriptor_copy_8ssbo                               |    23107 |   5.6% |
| 105 | descriptor_copy_1image                              |   139890 |  33.8% |
| 106 | descriptor_copy_16image                             |    62914 |  15.2% |
| 107 | descriptor_copy_1imagebuffer                        |   140130 |  33.8% |
| 108 | descriptor_copy_16imagebuffer                       |    63654 |  15.4% |
| 109 | descriptor_copy_mutable_1ubo                        |   142547 |  34.4% |
| 110 | descriptor_copy_mutable_12ubo                       |    29830 |   7.2% |
| 111 | descriptor_copy_mutable_1combined_sampler           |   139614 |  33.7% |
| 112 | descriptor_copy_mutable_16combined_sampler          |    41532 |  10.0% |
| 113 | descriptor_copy_mutable_1sampled_image              |   138477 |  33.4% |
| 114 | descriptor_copy_mutable_16sampled_image             |    40852 |   9.9% |
| 115 | descriptor_copy_mutable_1texelbuffer                |   139915 |  33.8% |
| 116 | descriptor_copy_mutable_16texelbuffer               |    40536 |   9.8% |
| 117 | descriptor_copy_mutable_1ssbo                       |   109567 |  26.4% |
| 118 | descriptor_copy_mutable_8ssbo                       |    23056 |   5.6% |
| 119 | descriptor_copy_mutable_1image                      |   140748 |  34.0% |
| 120 | descriptor_copy_mutable_16image                     |    62124 |  15.0% |
| 121 | descriptor_copy_mutable_1imagebuffer                |   140755 |  34.0% |
| 122 | descriptor_copy_mutable_16imagebuffer               |    64907 |  15.7% |

|   # | Misc Tests                                          | kop/s (besides zerovram) | % (ignore) |
| --: | --------------------------------------------------- | -------: | -----: |
| 124 | misc_resolve_4region                                |      238 | 100.0% |
| 125 | misc_resolve_4region_mismatched                     |      305 | 100.0% |
| 126 | misc_resolve_mutable                                |     1138 | 100.0% |
| 127 | misc_resolve_mutable_4region                        |      530 | 100.0% |
| 128 | misc_resolve_mutable_4region_mismatched             |      433 | 100.0% |
| 129 | misc_copy                                           |     1123 | 100.0% |
| 130 | misc_copy_4region                                   |      451 | 100.0% |
| 131 | misc_copy_4region_mismatched                        |      424 | 100.0% |
| 132 | misc_copy_mutable                                   |     1078 | 100.0% |
| 133 | misc_copy_mutable_4region                           |      465 | 100.0% |
| 134 | misc_copy_mutable_4region_mismatched                |      372 | 100.0% |
| 135 | misc_compile_fastlink_depthonly                     |      544 | 100.0% |
| 136 | misc_compile_fastlink_slow                          |      315 | 100.0% |
| --- | zerovram tests must be used with -fixed             | -------- | ------ |
| 137 | misc_zerovram                                       |        0 | unsupported (smh NVIDIA) |
| --- | zerovram tests must be used with -fixed             | -------- | ------ |
| 138 | misc_zerovram_manual                                |        0 | unsupported (smh NVIDIA) |

qwerty@qwerty-asus-g14:~/Projects/vkoverhead/builddir$ 
```

| Device Name                        | Driver Name | Driver Info |
| ---------------------------------- | ----------- | ----------- |
| NVIDIA GeForce RTX 3060 Laptop GPU | NVIDIA      | 535.86.05   |


|   # | Draw Tests                                          |    kop/s | % relative to 'draw' |
| --: | --------------------------------------------------- | -------: | -----: |
|   0 | draw                                                |    52647 | 100.0% |
|   1 | draw_multi                                          |   227737 | 432.6% |
|   2 | draw_vertex                                         |    54482 | 103.5% |
|   3 | draw_multi_vertex                                   |   225505 | 428.3% |
|   4 | draw_index_change                                   |    38426 |  73.0% |
|   5 | draw_index_offset_change                            |    38052 |  72.3% |
|   6 | draw_rp_begin_end                                   |     1395 |   2.7% |
|   7 | draw_rp_begin_end_dynrender                         |     1019 |   1.9% |
|   8 | draw_rp_begin_end_dontcare                          |     1925 |   3.7% |
|   9 | draw_rp_begin_end_dontcare_dynrender                |     1214 |   2.3% |
|  10 | draw_multirt                                        |    50316 |  95.6% |
|  11 | draw_multirt_dynrender                              |    49386 |  93.8% |
|  12 | draw_multirt_begin_end                              |      482 |   0.9% |
|  13 | draw_multirt_begin_end_dynrender                    |      400 |   0.8% |
|  14 | draw_multirt_begin_end_dontcare                     |      740 |   1.4% |
|  15 | draw_multirt_begin_end_dontcare_dynrender           |      645 |   1.2% |
|  16 | draw_vbo_change                                     |    35652 |  67.7% |
|  17 | draw_1vattrib_change                                |     8197 |  15.6% |
|  18 | draw_16vattrib                                      |    49680 |  94.4% |
|  19 | draw_16vattrib_16vbo_change                         |     9338 |  17.7% |
|  20 | draw_16vattrib_change                               |     8506 |  16.2% |
|  21 | draw_16vattrib_change_dynamic                       |     9299 |  17.7% |
|  22 | draw_16vattrib_change_gpl                           |      324 |   0.6% |
|  23 | draw_16vattrib_change_gpl_hashncache                |     4206 |   8.0% |
|  24 | draw_1ubo_change                                    |    21087 |  40.1% |
|  25 | draw_12ubo_change                                   |     4719 |   9.0% |
|  26 | draw_1combined_sampler_change                       |     9740 |  18.5% |
|  27 | draw_16combined_sampler_change                      |     9357 |  17.8% |
|  28 | draw_1texelbuffer_change                            |    21112 |  40.1% |
|  29 | draw_16texelbuffer_change                           |    19244 |  36.6% |
|  30 | draw_1ssbo_change                                   |    20787 |  39.5% |
|  31 | draw_8ssbo_change                                   |    17057 |  32.4% |
|  32 | draw_1image_change                                  |     9716 |  18.5% |
|  33 | draw_16image_change                                 |     9519 |  18.1% |
|  34 | draw_1imagebuffer_change                            |    20993 |  39.9% |
|  35 | draw_16imagebuffer_change                           |    20194 |  38.4% |
|  36 | draw_ubo_db_change                                  |     4523 |   8.6% |
|  37 | draw_ssbo_db_change                                 |    28640 |  54.4% |
|  38 | draw_combined_sampler_db_change                     |    28817 |  54.7% |
|  39 | draw_image_db_change                                |    28688 |  54.5% |

|   # | Submit Tests                                        |     op/s | % relative to 'submit_noop' |
| --: | --------------------------------------------------- | -------: | -----: |
|  40 | submit_noop                                         | 18453031 | 100.0% |
|  41 | submit_50noop                                       |  5127028 |  27.8% |
|  42 | submit_1cmdbuf                                      |   182807 |   1.0% |
|  43 | submit_50cmdbuf                                     |    12292 |   0.1% |
|  44 | submit_50cmdbuf_50submit                            |    12238 |   0.1% |

|   # | Descriptor Tests                                    |    kop/s | % relative to 'descriptor_noop' |
| --: | --------------------------------------------------- | -------: | -----: |
|  45 | descriptor_noop                                     |   414293 | 100.0% |
|  46 | descriptor_1ubo                                     |   107430 |  25.9% |
|  47 | descriptor_template_1ubo                            |    96163 |  23.2% |
|  48 | descriptor_template_1ubo_push                       |    81682 |  19.7% |
|  49 | descriptor_12ubo                                    |    21969 |   5.3% |
|  50 | descriptor_template_12ubo                           |    20922 |   5.1% |
|  51 | descriptor_template_12ubo_push                      |    12957 |   3.1% |
|  52 | descriptor_1combined_sampler                        |   120383 |  29.1% |
|  53 | descriptor_template_1combined_sampler               |   110941 |  26.8% |
|  54 | descriptor_template_1combined_sampler_push          |    93437 |  22.6% |
|  55 | descriptor_16combined_sampler                       |    25693 |   6.2% |
|  56 | descriptor_template_16combined_sampler              |    24574 |   5.9% |
|  57 | descriptor_template_16combined_sampler_push         |    12239 |   3.0% |
|  58 | descriptor_1sampled_image                           |   125789 |  30.4% |
|  59 | descriptor_template_1sampled_image                  |   121371 |  29.3% |
|  60 | descriptor_template_1sampled_image_push             |    93073 |  22.5% |
|  61 | descriptor_16sampled_image                          |    28869 |   7.0% |
|  62 | descriptor_template_16sampled_image                 |    28451 |   6.9% |
|  63 | descriptor_template_16sampled_image_push            |    12340 |   3.0% |
|  64 | descriptor_1texelbuffer                             |   162074 |  39.1% |
|  65 | descriptor_template_1texelbuffer                    |   144840 |  35.0% |
|  66 | descriptor_template_1texelbuffer_push               |    95636 |  23.1% |
|  67 | descriptor_16texelbuffer                            |    37076 |   8.9% |
|  68 | descriptor_template_16texelbuffer                   |    37256 |   9.0% |
|  69 | descriptor_template_16texelbuffer_push              |    12789 |   3.1% |
|  70 | descriptor_1ssbo                                    |   125223 |  30.2% |
|  71 | descriptor_template_1ssbo                           |   121922 |  29.4% |
|  72 | descriptor_template_1ssbo_push                      |    91633 |  22.1% |
|  73 | descriptor_8ssbo                                    |    38994 |   9.4% |
|  74 | descriptor_template_8ssbo                           |    40857 |   9.9% |
|  75 | descriptor_template_8ssbo_push                      |    20273 |   4.9% |
|  76 | descriptor_1image                                   |   126194 |  30.5% |
|  77 | descriptor_template_1image                          |   123875 |  29.9% |
|  78 | descriptor_template_1image_push                     |    99706 |  24.1% |
|  79 | descriptor_16image                                  |    53751 |  13.0% |
|  80 | descriptor_template_16image                         |    51054 |  12.3% |
|  81 | descriptor_template_16image_push                    |    26386 |   6.4% |
|  82 | descriptor_1imagebuffer                             |   171423 |  41.4% |
|  83 | descriptor_template_1imagebuffer                    |   154875 |  37.4% |
|  84 | descriptor_template_1imagebuffer_push               |    93859 |  22.7% |
|  85 | descriptor_16imagebuffer                            |    65844 |  15.9% |
|  86 | descriptor_template_16imagebuffer                   |    61643 |  14.9% |
|  87 | descriptor_template_16imagebuffer_push              |    25725 |   6.2% |
|  88 | descriptor_buffer_offset_ubo                        |   281042 |  67.8% |
|  89 | descriptor_buffer_offset_combined_sampler           |   304401 |  73.5% |
|  90 | descriptor_buffer_offset_sampled_image              |   353466 |  85.3% |
|  91 | descriptor_buffer_offset_texelbuffer                |   139405 |  33.6% |
|  92 | descriptor_buffer_offset_ssbo                       |   331791 |  80.1% |
|  93 | descriptor_buffer_offset_image                      |   304730 |  73.6% |
|  94 | descriptor_buffer_offset_imagebuffer                |   140123 |  33.8% |
|  95 | descriptor_copy_1ubo                                |   143032 |  34.5% |
|  96 | descriptor_copy_12ubo                               |    29575 |   7.1% |
|  97 | descriptor_copy_1combined_sampler                   |   140687 |  34.0% |
|  98 | descriptor_copy_16combined_sampler                  |    41363 |  10.0% |
|  99 | descriptor_copy_1sampled_image                      |   138371 |  33.4% |
| 100 | descriptor_copy_16sampled_image                     |    40806 |   9.8% |
| 101 | descriptor_copy_1texelbuffer                        |   140494 |  33.9% |
| 102 | descriptor_copy_16texelbuffer                       |    40330 |   9.7% |
| 103 | descriptor_copy_1ssbo                               |   108785 |  26.3% |
| 104 | descriptor_copy_8ssbo                               |    23107 |   5.6% |
| 105 | descriptor_copy_1image                              |   139890 |  33.8% |
| 106 | descriptor_copy_16image                             |    62914 |  15.2% |
| 107 | descriptor_copy_1imagebuffer                        |   140130 |  33.8% |
| 108 | descriptor_copy_16imagebuffer                       |    63654 |  15.4% |
| 109 | descriptor_copy_mutable_1ubo                        |   142547 |  34.4% |
| 110 | descriptor_copy_mutable_12ubo                       |    29830 |   7.2% |
| 111 | descriptor_copy_mutable_1combined_sampler           |   139614 |  33.7% |
| 112 | descriptor_copy_mutable_16combined_sampler          |    41532 |  10.0% |
| 113 | descriptor_copy_mutable_1sampled_image              |   138477 |  33.4% |
| 114 | descriptor_copy_mutable_16sampled_image             |    40852 |   9.9% |
| 115 | descriptor_copy_mutable_1texelbuffer                |   139915 |  33.8% |
| 116 | descriptor_copy_mutable_16texelbuffer               |    40536 |   9.8% |
| 117 | descriptor_copy_mutable_1ssbo                       |   109567 |  26.4% |
| 118 | descriptor_copy_mutable_8ssbo                       |    23056 |   5.6% |
| 119 | descriptor_copy_mutable_1image                      |   140748 |  34.0% |
| 120 | descriptor_copy_mutable_16image                     |    62124 |  15.0% |
| 121 | descriptor_copy_mutable_1imagebuffer                |   140755 |  34.0% |
| 122 | descriptor_copy_mutable_16imagebuffer               |    64907 |  15.7% |

|   # | Misc Tests                                          | kop/s (besides zerovram) | % (ignore) |
| --: | --------------------------------------------------- | -------: | -----: |
| 124 | misc_resolve_4region                                |      238 | 100.0% |
| 125 | misc_resolve_4region_mismatched                     |      305 | 100.0% |
| 126 | misc_resolve_mutable                                |     1138 | 100.0% |
| 127 | misc_resolve_mutable_4region                        |      530 | 100.0% |
| 128 | misc_resolve_mutable_4region_mismatched             |      433 | 100.0% |
| 129 | misc_copy                                           |     1123 | 100.0% |
| 130 | misc_copy_4region                                   |      451 | 100.0% |
| 131 | misc_copy_4region_mismatched                        |      424 | 100.0% |
| 132 | misc_copy_mutable                                   |     1078 | 100.0% |
| 133 | misc_copy_mutable_4region                           |      465 | 100.0% |
| 134 | misc_copy_mutable_4region_mismatched                |      372 | 100.0% |
| 135 | misc_compile_fastlink_depthonly                     |      544 | 100.0% |
| 136 | misc_compile_fastlink_slow                          |      315 | 100.0% |
| --- | zerovram tests must be used with -fixed             | -------- | ------ |
| 137 | misc_zerovram                                       |        0 | unsupported (smh NVIDIA) |
| --- | zerovram tests must be used with -fixed             | -------- | ------ |
| 138 | misc_zerovram_manual                                |        0 | unsupported (smh NVIDIA) |

**Comment by qwertychouskie** [comment]
Also why does test `#123` seem to not exist?

**Comment by qwertychouskie** [comment]
![image](https://github.com/zmike/vkoverhead/assets/13989090/cb37a115-529c-426e-8fcd-436eb8753d5a)

**Comment by qwertychouskie** [comment]
Does it matter if `Device Name`/`Driver Name`/`Driver Info` are in CSV format or not, considering they originally were not in CSV format?

**Comment by zmike** [comment]
Nah you can leave that stuff as-is.
