### ISSUE TITLE
Cannot directly run the whole test set with fixed iteration count

### ISSUE THREAD

**Issue by CreativeCylon** [zmike/vkoverhead#30]
I was trying to run the entire list with a fixed iteration count and came across this. Is this restriction necessary?

https://github.com/zmike/vkoverhead/blob/c861898263052a85183b9334627126f16480334a/src/vkoverhead.c#L3271-L3274

One can just run `vkoverhead -start 0 -fixed #count` as a workaround. Should that check be removed, or am I missing something?

**Comment by zmike** [comment]
I think the check exists because the iteration count meanings vary between different types of tests, so the theory was that running the whole suite in that mode probably meant that you didn't really know what you were doing.

**Comment by turol** [comment]
I wrote the original version of that and @zmike is exactly right. The iteration counts can vary by several orders of magnitude.
