### ISSUE TITLE
-output-only now prints spam

### ISSUE THREAD

**Issue by turol** [zmike/vkoverhead#6]
-output-only now prints the messages from this:
https://github.com/zmike/vkoverhead/blob/0c0ad7005bac990b70ef1d6a22ef4c62213a5918/src/vkoverhead.c#L2693

Looks like it was broken by 0c0ad7005bac990b70ef1d6a22ef4c62213a5918. I think previously the broken check was always hiding this message. Now that it has been fixed the above `output_only` check should be extended to this bit of code.

**Comment by zmike** [comment]
whoops
